//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasRC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyHeader
    {
        public int Id { get; set; }
        public int SurveyId { get; set; }
        public string Customer { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> SurveyEnded { get; set; }
        public string UserLogged { get; set; }
    }
}
