//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasRC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyDetail
    {
        public int Id { get; set; }
        public int SurveyHeaderId { get; set; }
        public int QuestionId { get; set; }
        public int AnswerId { get; set; }
        public int Points { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
